export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_BY_USERNAME="GET_USER_BY_USERNAME"
export const GET_USERS_BY_USER_IDS="GET_USERS_BY_USER_IDS"
export const FOLLOW_USER="FOLLOW_USER";
export const UNFOLLOW_USER="UNFOLLOW_USER";
export const SEARCH_USER="SEARCH_USER";
export const UPDATE_USER="UPDATE_USER";
